
I believe using the compiler as an assistant while developing compositional, verified software can enable us to scale said software to sizes orders of magnitude larger. It allows us to reason about and design these large-scale systems while carefully managing their complexity and their emergent behavior.
Using types in programming is, in a sense, bootstrapping myself and allowing the computer to think about my code for me.
I tell it very roughly what to do and it checks I'm doing that. 
Static typing is bootstrapping myself and allowing the computer to think about my code for me. 

* Why study intelligence?
 - We need to boostrap ourselves
* How to study intelligence?
 - Using Category theory

"The concept of _intelligence_ is strongly linked to _life_, _self-regulating systems_, and [entropy](https://en.wikipedia.org/wiki/What_Is_Life%3F).

The goal overlaps with many of the goals of the field of [Artificial Intelligence (AI)](https://en.wikipedia.org/wiki/Artificial_intelligence). However, I don't believe [either](https://abstrusegoose.com/215) of [those](https://en.wikipedia.org/wiki/Intelligence#Definitions) two words are properly defined.


They frame neural networks as a cooperative multi-player game, where some players depend on other ones to learn, but can be trained in an asynchronous manner.

Category theory is proving to a useful _tool for thought_. It guides me _how_ to think. It prompts me to ask questions which integrate new ideas more firmly into the existing web of knowledge. It allows me to [compress a very specific abstract thought down to its deep essence](CT as thought compression).

If we consider life as an emergent property of the universe - composition of systems at various levels... it's fascinating that these systems 
simple, reductionistic physical cells interacting 
As animals who evolved throughout millenia in various hostile environments, it's fascinating that 

As somebody who's interested in understanding how one special case of _intelligence_ works - the brain, I have to ask myself one thing.
Does intelligent behavior exhibit properties of internal data compression in 
Which brain I'm interested in understanding - the one which is aware of the guiding principles of the category theory, or the one which isn't?
Am I interested in understanding how the pre-category theory brain works, or post-category theory?
which isn't aware of category theory works, or the brain which is?
As amachine learning researcher - I have to ask - what 
The monkey brain inside my skull, evolved throughout millenia is full of emotions, irrational hopes and dreams, beliefs and unconscious thoughts I have limited control over.

I'm interested in understanding the fundamental principles of intelligence through the lens of category theory.


I want to understanding and designing large-scale systems while carefully managing their complexity and emergent behavior.

Some papers and blogs which are a strong inspiration for me:

* [On Compositionality](https://julesh.com/2017/04/22/on-compositionality/)
* [Backprop as Functor](https://arxiv.org/abs/1711.10455)
* [The simple essence of automatic differentiation](http://conal.net/papers/essence-of-ad/)

Category theory books:

* [Conceptual Mathematics: A First Introduction to Categories](https://www.amazon.com/Conceptual-Mathematics-First-Introduction-Categories/dp/052171916X)
* [Seven Sketches in Compositionality: An Invitation To Applied Category Theory](https://arxiv.org/abs/1803.05316)
